function [ Revenue ] = Beam_rev( FOS )
%Calculates the revenue generated by a beam design based on its factor of
%safety
%   Based on a HARA function for the value of the beam relative to its FOS

%HARA parameters
gamma=18;
b=1.4;
a=1;
scale=1500; %Used to scale result to the right range

%calculate utility for a 0 Margin of Safety (MOS) beam (establishes a
%baseline to subtract utility function from)

u_0=(1-gamma)/gamma*(a*0/(1-gamma)+b)^gamma;
%calculate utility for the beam and convert FOS to MOS (MOS=FOS-1)

u_1=(1-gamma)/gamma*(a*(FOS-1)/(1-gamma)+b)^gamma;
%Determine revenue
Revenue=scale*u_1-scale*u_0;
end

